spring.application.name=stray-animal-rescue-platform
spring.datasource.url=${DB_URL:jdbc:h2:mem:stray_animal_rescue;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1}
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
